# -*- coding: utf-8 -*-
"""Web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdwkszpdQKqTjNTU__8WtcGD0aWajWhW
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def scrape_books():
    url = "http://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html"

    try:
        response = requests.get(url)
        if response.status_code != 200:
            print(f"Error {response.status_code}")
            return

        soup = BeautifulSoup(response.content, 'html.parser')
        products = []
        items = soup.find_all('article', class_='product_pod')

        for item in items:
            title = item.find('h3').find('a')['title']
            price = item.find('p', class_='price_color').get_text(strip=True)

            products.append({
                "Book Title": title,
                "Price": price,
                "Availability": "In Stock"
            })
        df = pd.DataFrame(products)
        df.to_csv('data2.csv', index=False)
        print(f"Success! {len(products)} books saved to data2.csv")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    scrape_books()