# -*- coding: utf-8 -*-
"""Web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdwkszpdQKqTjNTU__8WtcGD0aWajWhW
"""

import requests
import pandas as pd
import time

def scrape_shopify():
    url = "https://www.allbirds.com/products.json"
    headers = {"User-Agent": "Mozilla/5.0"}

    response = requests.get(url, headers=headers)
    data = response.json()

    products_list = []
    for item in data['products']:
        products_list.append({
            "Title": item['title'],
            "Price": item['variants'][0]['price'],
            "Type": item['product_type']
        })
        time.sleep(1)

    df = pd.DataFrame(products_list)
    df.to_csv('data3.csv', index=False)
    print("Shopify data saved to data3.csv!")

if __name__ == "__main__":
    scrape_shopify()

