# -*- coding: utf-8 -*-
"""Web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdwkszpdQKqTjNTU__8WtcGD0aWajWhW
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def scrape_books():
    url = "http://books.toscrape.com/catalogue/page-1.html"
    headers = {"User-Agent": "Mozilla/5.0"}

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    books = []
    # Finding all book containers
    articles = soup.find_all('article', class_='product_pod')

    for article in articles:
        # Extracting data fields
        title = article.h3.a['title']
        price = article.find('p', class_='price_color').text.strip()
        availability = article.find('p', class_='instock availability').text.strip()

        books.append({
            "Title": title,
            "Price": price,
            "Availability": availability
        })

        # Ethical scraping: pause for 1 second
        time.sleep(1)

    # Save to CSV
    df = pd.DataFrame(books)
    df.to_csv('data.csv', index=False)
    print("Scraping complete. data.csv created.")

if __name__ == "__main__":
    scrape_books()